import { Frame, Sticker } from "./types";

export const FRAMES: Frame[] = [
  {
    id: "pink-heart",
    name: "Pink Heart",
    emoji: "💗",
    description: "Hearts, bows, and sparkles",
  },
  {
    id: "scrapbook",
    name: "Scrapbook",
    emoji: "📒",
    description: "Tape, flowers, and doodles",
  },
  {
    id: "miles-apart",
    name: "Miles Apart",
    emoji: "🌍",
    description: "Together at heart",
  },
  {
    id: "cloud-stars",
    name: "Cloud & Stars",
    emoji: "☁️",
    description: "Dreamy night sky",
  },
  {
    id: "bear-bunny",
    name: "Bear & Bunny",
    emoji: "🧸",
    description: "Cute animal friends",
  },
  {
    id: "love-letter",
    name: "Love Letter",
    emoji: "💌",
    description: "Envelope and stamps",
  },
  {
    id: "polaroid",
    name: "Polaroid",
    emoji: "📸",
    description: "Classic instant photo",
  },
  {
    id: "photobooth-strip",
    name: "Photo Strip",
    emoji: "🎞️",
    description: "4-photo strip layout",
  },
  {
    id: "same-moment",
    name: "Same Moment",
    emoji: "🕐",
    description: "Date and location",
  },
];

export const STICKERS: Sticker[] = [
  { id: "s1", emoji: "❤️", label: "Red Heart", category: "hearts" },
  { id: "s2", emoji: "💕", label: "Two Hearts", category: "hearts" },
  { id: "s3", emoji: "💖", label: "Sparkling Heart", category: "hearts" },
  { id: "s4", emoji: "💗", label: "Growing Heart", category: "hearts" },
  { id: "s5", emoji: "💘", label: "Heart Arrow", category: "hearts" },
  { id: "s6", emoji: "💝", label: "Gift Heart", category: "hearts" },
  { id: "s7", emoji: "🌟", label: "Glowing Star", category: "stars" },
  { id: "s8", emoji: "⭐", label: "Star", category: "stars" },
  { id: "s9", emoji: "✨", label: "Sparkles", category: "stars" },
  { id: "s10", emoji: "💫", label: "Dizzy", category: "stars" },
  { id: "s11", emoji: "🎀", label: "Ribbon", category: "bows" },
  { id: "s12", emoji: "bow", label: "Cute Bow", category: "bows" },
  { id: "s13", emoji: "🌸", label: "Cherry Blossom", category: "flowers" },
  { id: "s14", emoji: "🌺", label: "Hibiscus", category: "flowers" },
  { id: "s15", emoji: "🌷", label: "Tulip", category: "flowers" },
  { id: "s16", emoji: "🌼", label: "Blossom", category: "flowers" },
  { id: "s17", emoji: "🐻", label: "Bear", category: "cute" },
  { id: "s18", emoji: "🐰", label: "Bunny", category: "cute" },
  { id: "s19", emoji: "🦋", label: "Butterfly", category: "cute" },
  { id: "s20", emoji: "🐱", label: "Cat", category: "cute" },
  { id: "s21", emoji: "💌", label: "Love Letter", category: "love" },
  { id: "s22", emoji: "💑", label: "Couple", category: "love" },
  { id: "s23", emoji: "💏", label: "Kiss", category: "love" },
  { id: "s24", emoji: "🥰", label: "Love Face", category: "love" },
  { id: "s25", emoji: "☁️", label: "Cloud", category: "nature" },
  { id: "s26", emoji: "🌙", label: "Moon", category: "nature" },
  { id: "s27", emoji: "🌈", label: "Rainbow", category: "nature" },
  { id: "s28", emoji: "🎵", label: "Music", category: "cute" },
  { id: "s29", emoji: "📷", label: "Camera", category: "cute" },
  { id: "s30", emoji: "🧸", label: "Teddy Bear", category: "cute" },
];

export const FILTERS = [
  { id: "none", name: "Original", css: "none" },
  { id: "warm", name: "Warm", css: "saturate(1.2) sepia(0.15)" },
  { id: "cool", name: "Cool", css: "saturate(0.9) hue-rotate(10deg)" },
  { id: "soft", name: "Soft", css: "brightness(1.1) saturate(0.85)" },
  { id: "vintage", name: "Vintage", css: "sepia(0.4) saturate(1.2) brightness(0.95) contrast(1.05)" },
  { id: "dreamy", name: "Dreamy", css: "brightness(1.05) contrast(0.95) saturate(1.1)" },
  { id: "pastel", name: "Pastel", css: "brightness(1.15) saturate(0.7) contrast(0.9)" },
  { id: "rosy", name: "Rosy", css: "sepia(0.1) saturate(1.3) hue-rotate(-5deg)" },
  { id: "noir", name: "B&W", css: "grayscale(1)" },
  { id: "sepia", name: "Sepia", css: "sepia(0.7) saturate(1.1)" },
  { id: "film", name: "Film", css: "sepia(0.2) contrast(1.15) saturate(0.9) brightness(0.95)" },
  { id: "lomo", name: "Lomo", css: "contrast(1.4) saturate(1.3) brightness(0.9)" },
  { id: "cross-process", name: "Cross Process", css: "sepia(0.15) hue-rotate(15deg) saturate(1.4) contrast(1.1)" },
  { id: "dramatic", name: "Dramatic", css: "contrast(1.3) saturate(0.7) brightness(0.9)" },
  { id: "fade", name: "Fade", css: "brightness(1.1) contrast(0.85) saturate(0.8)" },
  { id: "vivid", name: "Vivid", css: "saturate(1.6) contrast(1.1)" },
  { id: "golden-hour", name: "Golden Hour", css: "sepia(0.25) saturate(1.3) brightness(1.05) hue-rotate(-10deg)" },
  { id: "moody", name: "Moody", css: "brightness(0.9) contrast(1.2) saturate(0.8) hue-rotate(5deg)" },
  { id: "polaroid", name: "Polaroid", css: "sepia(0.1) saturate(1.15) brightness(1.05) contrast(1.05)" },
  { id: "matte", name: "Matte", css: "brightness(1.05) contrast(0.9) saturate(0.85) sepia(0.05)" },
  { id: "glam", name: "Glam", css: "brightness(1.1) contrast(1.1) saturate(1.2)" },
  { id: "bw-warm", name: "B&W Warm", css: "grayscale(1) sepia(0.2) brightness(1.05)" },
  { id: "bw-cool", name: "B&W Cool", css: "grayscale(1) hue-rotate(10deg) brightness(1.05)" },
];

export const AVATARS = [
  { id: "bear", emoji: "🐻", label: "Bear" },
  { id: "bunny", emoji: "🐰", label: "Bunny" },
  { id: "cat", emoji: "🐱", label: "Cat" },
  { id: "panda", emoji: "🐼", label: "Panda" },
  { id: "fox", emoji: "🦊", label: "Fox" },
  { id: "penguin", emoji: "🐧", label: "Penguin" },
  { id: "owl", emoji: "🦉", label: "Owl" },
  { id: "dog", emoji: "🐶", label: "Dog" },
  { id: "hamster", emoji: "🐹", label: "Hamster" },
  { id: "unicorn", emoji: "🦄", label: "Unicorn" },
  { id: "turtle", emoji: "🐢", label: "Turtle" },
  { id: "frog", emoji: "🐸", label: "Frog" },
];

export const SAMPLE_MEMORIES = [
  {
    id: "mem1",
    caption: "Our first virtual photobooth",
    date: "July 20, 2026",
    frame: "pink-heart" as const,
    emoji: "📸",
  },
  {
    id: "mem2",
    caption: "Same moment, different places",
    date: "July 22, 2026",
    frame: "miles-apart" as const,
    emoji: "🌍",
  },
  {
    id: "mem3",
    caption: "Late night cuddle session",
    date: "July 23, 2026",
    frame: "cloud-stars" as const,
    emoji: "🌙",
  },
  {
    id: "mem4",
    caption: "Just because I love you",
    date: "July 23, 2026",
    frame: "love-letter" as const,
    emoji: "💌",
  },
  {
    id: "mem5",
    caption: "Date night across the miles",
    date: "July 21, 2026",
    frame: "polaroid" as const,
    emoji: "💕",
  },
  {
    id: "mem6",
    caption: "Matching smiles, different cities",
    date: "July 19, 2026",
    frame: "scrapbook" as const,
    emoji: "😊",
  },
];
