services:
  - type: web
    name: togetherframe-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        value: "postgresql://togetherframe_db_user:HCwStg2xfrI7svSGdWhkQS8UpcwSQcW5@dpg-d9h4gtnavr4c73beoq8g-a/togetherframe_db"
      - key: SECRET_KEY
        value: "togetherframe-prod-secret-2026"
      - key: PYTHON_VERSION
        value: "3.12.8"
